### ISSUE TITLE
Add ability to make a static build

### ISSUE THREAD

**Issue by saghul** [saghul/sjs#47]
Not sure how to handle dynamic modules though, what would they link with? The CLI? The embedding application?

**Comment by sgmesservey** [comment]
On linux, and OSX (homebrew? not XCode, at any rate) you simply compile the application with -rdynamic in CFLAGS, or -export-dynamic in LDFLAGS (gcc and ld flags, respectively).
This exports all symbols, so that when dynamic libraries are loaded, they transparently bind to the application.

**Comment by saghul** [comment]
This is now the default. In addition, the executable is already built with `-rdynamic`, since CMake defaults to that.
